version: 2
jobs:
  build:
    working_directory: ~/circleci-spring

    docker:
      - image: openjdk:jdk-alpine

    steps:

      - checkout
- setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            mvn install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - restore_cache:
          key: circleci-spring-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-spring-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/springbootms-0.0.1-SNAPSHOT.jar

workflows:
  version: 2
  build_and_test:
    jobs:
      - build