# Check https://circleci.com/docs/2.0/language-java/ for more details
#

version: 2
jobs:
  build:
  working_directory: ~/spring-repo
  
  docker:
      - image: openjdk:jdk-alpine
          
    steps:
      - checkout
     
      # Download and cache dependencies
      - restore_cache:
          keys:
          - pom-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - pom-dependencies-

      - run: mvn package

      - save_cache:
          paths:
            - ~/.m2
          key: pom-dependencies-{{ checksum "pom.xml" }}

# run tests!
      - run: mvn integration-test
     # Build application
      - run: mvn package
      
      #Store output of build
      - store_artifacts:
          path: target/springms-0.0.1-SNAPSHOT.jar
          
