version: 2
jobs:
  build:
    working_directory: ~/circleci-spring
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            mvn install
      - restore_cache:
          key: springms-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: springms-{{ checksum "pom.xml" }}
      - run: 
          name: building package
          command: |
            mvn package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/springbootms.jar
      - run:
          name: build and push Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t khajapm/fullstackdemo-docker:$TAG .
            docker login --username=${USER_NAME} --password=${USER_PASS}
            docker push khajapm/fullstackdemo-docker:$TAG
